In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
os.getcwd() # 获取当前工作路径

'F:\\Study\\note\\1.笔记\\数据分析\\python数据分析'

In [ ]:
os.chdir('F:\Study\note\1.笔记\数据分析') # 修改工作路径

In [4]:
df = pd.read_excel('2014年各省市售电量.xlsx',encoding='gbk')

In [5]:
df

,省市,地市,统计周期,用电类别,当期值,累计值,同期值,同期累计值,月度计划值
0,安徽,NaN,2014-01-01,大工业,44298.592143,44298.592143,52272.338729,52272.338729,57588.169786
1,安徽,NaN,2014-01-01,非居民,6283.597857,6283.597857,7414.645471,7414.645471,8168.677214
2,安徽,NaN,2014-01-01,非普工业,8159.322143,8159.322143,9628.000129,9628.000129,10607.118786
3,安徽,NaN,2014-01-01,汇总,76419.143571,76419.143571,90174.589414,90174.589414,99344.886643
4,安徽,NaN,2014-01-01,居民,16845.201429,16845.201429,19877.337686,19877.337686,21898.761857
...,...,...,...,...,...,...,...,...,...
7418,重庆,重庆市区,2014-02-01,商业,2323.944286,2012.500000,1113.831793,2168.536407,2616.250000
7419,重庆,重庆市区,2014-03-01,商业,2260.532143,2817.000000,1007.335257,2851.871664,3662.100000
7420,重庆,重庆市区,2014-04-01,商业,2296.353571,3657.357143,2709.697214,10838.788857,4754.564286
7421,重庆,重庆市区,2014-05-01,商业,2310.835714,4512.214286,2726.786143,13633.930714,5865.878571
7422,重庆,重庆市区,2014-06-01,商业,2491.732143,5547.928571,1395.545000,3923.416664,7212.307143

In [ ]:
df.head(5)
df.tail(5)

In [9]:
df.dtypes

省市               object
地市               object
统计周期     datetime64[ns]
用电类别             object
当期值             float64
累计值             float64
同期值             float64
同期累计值           float64
月度计划值           float64
dtype: object

In [10]:
df = pd.read_excel('2014年各省市售电量.xlsx',\
                   encoding='gbk',nrows=10,sep=',')

In [11]:
df

,省市,地市,统计周期,用电类别,当期值,累计值,同期值,同期累计值,月度计划值
0,安徽,NaN,2014-01-01,大工业,44298.592143,44298.592143,52272.338729,52272.338729,57588.169786
1,安徽,NaN,2014-01-01,非居民,6283.597857,6283.597857,7414.645471,7414.645471,8168.677214
2,安徽,NaN,2014-01-01,非普工业,8159.322143,8159.322143,9628.000129,9628.000129,10607.118786
3,安徽,NaN,2014-01-01,汇总,76419.143571,76419.143571,90174.589414,90174.589414,99344.886643
4,安徽,NaN,2014-01-01,居民,16845.201429,16845.201429,19877.337686,19877.337686,21898.761857
5,安徽,NaN,2014-01-01,农业,2214.409286,2214.409286,2613.002957,2613.002957,2878.732071
6,安徽,NaN,2014-01-01,其他,1753.479286,1753.479286,2069.105557,2069.105557,2279.523071
7,安徽,NaN,2014-01-01,商业,5549.767857,5549.767857,6548.726071,6548.726071,7214.698214
8,北京,昌平,2014-05-01,大工业,2181.299286,870.285714,2573.933157,12869.665786,1131.371429
9,北京,昌平,2014-05-01,非居民,1703.193571,392.214286,2009.768414,10048.842071,509.878571

In [17]:
df.to_csv('df.csv',index=False,encoding='gbk')